### ISSUE TITLE
Data format in jailbreak device-tree

### ISSUE THREAD

**Issue by oschanger** [Siguza/iokit-utils#1]
When i dumped device-tree info on my jailbreak device.I got something like this:
memory-frequency Data <0008af2f 00000000>
I wonder what is this 'Data' format.Some of the raw data is Base64 encoded.
Others i can't get the value

**Comment by Siguza** [comment]
Been a while, but I just pushed a relevant change.  
`ioprint` now has a `-j` option that dumps properties in a JSON-like format, and CFData objects are fully hex-dumped with ASCII on the side.
