### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by stek29** [Siguza/iokit-utils#4]
hi, I'm collecting various tools and libs at https://github.com/stek29/homebrew-idevice, so I was wondering - what is the current licensing for iokit-utils?

**Comment by Siguza** [comment]
I'll have to formally add the license to the repo, but it's gonna be "MPL2 with Exhibit B" - except for `iokit.h`, which I'll place in the public domain.

**Comment by Siguza** [comment]
Alright, proper license added.
